### PR TITLE
Remove hardcoded atlassian.net domain

### PR DESCRIPTION
**Pull request by artizirk**
This will enable to use a self hosted Jira instance on a custom domain.

### CODE REVIEW

**Comment by jefgen** [comment]
Thank you for the Pull-Request! I hope the extension was useful.
Your changes look fine, so I will go ahead and merge them.
Thanks again.

**Comment by artizirk** [comment]
Thank you for merging it. Can you also push a new version to addons.mozilla.org?

**Comment by jefgen** [comment]
I pushed a new version, if you check for updates it should hopefully show up.

**Comment by artizirk** [comment]
Awesome, thank you!

**Pull request merged**
